name: 自动无缝翻页 - 申请添加支持 (Autopage request)
description: 自动无缝翻页 脚本 申请添加支持 xxx 网站...
title: "[自动无缝翻页] 申请添加支持 xxx 网站（记得修改该标题示例，并移除该括号提示）"
labels: 功能建议
body:
  - type: markdown
    attributes:
      value: |
        > [!NOTE]
        > ***注意：因为精力有限，目前主要维护现有规则，想要让我花费时间和精力帮你写规则，就请务必看完以下 `申请必读` ！***
        ****
        发之前，请先搜下有没有类似的 [**Issues**](https://github.com/XIU2/UserScript/issues) （包括[**关闭**](https://github.com/XIU2/UserScript/issues?q=is%3Aissue+is%3Aclosed)的），请勿重复发起！  

        > [!IMPORTANT]
        > ### \# 申请必读：
        > 1. 请先确认 **`不是动态加载内容`** 的网站（**鼠标指向页码，左下角不显示链接即代表是动态加载**），这类网站无法制作规则。
        > 2. 如 **`需要登录`** 才能看到内容（无论注册有多简单），请**告诉我账号**，否则我**无法凭空制作**翻页规则（网课类不会支持）。 
        > 3. 请直接提供 **`具体页面的网页地址 URL`** （特别是一些**页面很多的网站**），尽量减少我的工作量，否则可能拒绝申请。  
        > 4. 对于 **`正版小说/漫画`** 网站，因为**反爬防盗**的原因也会导致无法制作规则（该脚本本质上也是爬虫，虽然只爬取下一页，但也会被阻碍）。  
        > 5. 对于 **`没有 HTTPS`** 的网站（这种网站目前全网占比极少，且大都是一些老旧网站），是不考虑添加支持的。  
        > 6. 如果你要申请对 `某个博客/论坛系统` 添加支持（即通用规则，所有使用这个博客/论坛系统的网站都会支持），那么需要提供 `官方博客/论坛地址` 及 其他**几个使用该博客/论坛系统的网站地址**，用于对比、验证，才能写出通用规则。

        > - 对于需要登录才能看的网页，哪怕注册再简单我也不会去主动注册，你可以用一些 **`阅后即焚`** 的网站来告诉我你的账号密码（毕竟 Github 没有私信功能，你可以提前把密码改成别的，我用完了你再改回去），也可以用各种 **`在线临时邮箱`** 网站随便申请个账号给我用，但不管如何你必须提供一个账号给我才能编写规则，这是基本原则。
        ****
  - type: input
    id: websitename
    attributes:
      label: 申请添加支持的 网站名称
      description: 必填，网站名字叫什么？方便我一眼识别网站类型
      placeholder: 请输入...
    validations:
      required: true
  - type: textarea
    id: webaddress
    attributes:
      label: 申请添加支持的 网页地址
      description: 必填，请提供要添加自动翻页支持的 **`具体网页地址 URL`**（各类希望添加支持的页面地址都要写上，如首页、分类页、搜索页、阅读页什么的），***请勿只提供一个网站首页地址***（除非你只需要对 首页 添加支持），否则可能会直接拒绝申请。
      placeholder: https://xxx
    validations:
      required: true